GET http://localhost:8888/api/customers
Authorization: Bearer CfDJ8KJLVT132c9Fg8xq647wbY9_oLB36v_dT1XbxaOFioymDze1kwIrYOQ7Oralai5OCWzOzpSFJjeAVfDFxZh9ox5ZQ1-F1c_jKfqCB0waYhcVkvm2JQfuUR24EQRNMmDXrc3FlpQKwn9ZtCtlA9Fr3eZ9-4CZ-6geJpAYdefS-Zgp7KlQmXKG2RIme9pMnWYrrynIM0NkDq1yIhKTJRkIHDfixnUHwEQwueWGjtG3Z6KTGKgWr1_u0y_1i6ofdyfIOYsnTYdsRGKAsxAguMnyh14DB7tX66m4L0iKjxfL6jv5CEw4E8u2EQtZlFh02khrMuJwwz81nKW1QrYbGF20tIgYQ7fuUpLBTwiJ4f6q5iNESWCanY1mvIOBMgB4B1AdBOJx6KIGG8XIPZJyISWT21aQAUCFbno2ZFKjVz8cviRSamgem60puW7Rr1HKXIQh4YmFbUTGUPO2hdbCjoxNh6XidERpMUuCpwciHbu65AkrmVHk-pEi2-l_1OCfgzpEgx3PiEC6DrxTPEfpKsrx3YtYQGVKRghBofmMFVQt3uDnolnvyrDpGCNZzjgdHnnPwE0NEvlbJ7tDVvseJDjjFWTZtHv7I1psNIDU1ZOv9Qn2eda2ulXZ9QOfsrRn7uCwTa7F0YeiaAtKNpSBQlHpndrie3YQM3tiZHCJz314XRJ_co25i96MxHc5Puesw6ldTw

###

GET http://localhost:8888/api/customers?withAddresses=true

###

GET http://localhost:8888/api/customers/1

###

GET http://localhost:8888/api/timebills/9
Authorization: Bearer CfDJ8KJLVT132c9Fg8xq647wbY-li-bVzrKMshi-RhuAtnu7KwNi7vXoPYa0oRp2sOWsZsrtVIrMW9yJ3uh4uEBN0lvQ6BaSLvoeBITeQJww5-wwUBDpG-3Y0CkEGL6VRxVY6SWi-dDLA5me4oQP-cTgfuRqKCieagHx5AJW2tGUv8_3CuC2c5Sb5EuGnXHoGXsXr_JX-n7gvtYFh18274hRq1rI_nzhd62qSpbuCbmKh8WKHQK-aEdBvGvx5AXKk29_3mZ3zyF9QYdKYf0yQjPmn2tYunW_4t3N6OWEGY1pjzWmPS1vjt_5HpOkV16zCMMeHrnEOTvzM26pnjhMGXr00e7rqmNbrEx1rJueK6l4ooQobx7foZeM3rIDJ_vOt8H1PS_YB2BX0KXUC4pNGMvIrCPlqKJG6Esxz2JYtV2fdGKCJFLQx5h5Qcuyc9H8DoTMHgN69aRo49itcHe4EKxnmvmZ2XnTWPziSDPlKaLu5Gvg5iQq9MeQ0jLkskjP9PnM05NO9tsOS6iOkQCecxZ8lVmQDMYMev8a_GxueI93ktgIZm2qcmdJzGbdSk42fz45KgKXzokiu03INGwkGsn08xNvtDRBa18axjqlo4HSAW-7VjGmqIOZtFfDXyBDSakpcny1jUNjN1W-axbE_FC0ko1k6qzn1sgIz_eUIsNQR66ampOUgct7mJZn_OuP9P5Zgg

###

POST http://localhost:8888/api/timebills
Content-Type: application/json

{
    "hoursWorked": 3.0,
    "rate": 250.00,
    "date": "2023-05-05",
    "work": "I did a thing...",
    "customerId": 1,
    "employeeId": 1
}

###

GET http://localhost:8888/api/customers/1/timebills

###

GET http://localhost:8888/api/customers/1/timebills/10

### 

POST http://localhost:8888/api/auth/login
Content-Type: application/json

{
    "email": "name@example.com",
    "password": "1234qwE!"
}