GET http://localhost:8888/api/customers
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJtYWdhcmVAZXhhbXBsZS5jb20iLCJqdGkiOiJjNTM2ODMxMy04ODBlLTRmNzQtODY5OC03Zjc4MTllNDVmMTEiLCJ1bmlxdWVfbmFtZSI6Im1hZ2FyZUBleGFtcGxlLmNvbSIsImV4cCI6MTc4MjA3ODA4OSwiaXNzIjoiaHR0cDovL2xvY2FsaG9zdDo1MDAwIiwiYXVkIjoiaHR0cDovL2xvY2FsaG9zdDo1MDAwIn0.gMBh3ft2yRybWSvIAjQcFzXjsBUMkVWZVPOcb78nAM4

###

GET http://localhost:8888/api/customers?withAddresses=true

###

GET http://localhost:8888/api/customers/1

###

GET http://localhost:8888/api/timebills/9
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJtYWdhcmVAZXhhbXBsZS5jb20iLCJqdGkiOiJkNzgxNTNjNC1iYjM5LTQwNjYtYTUxNy1hMGFhMDcwMTEyOWUiLCJ1bmlxdWVfbmFtZSI6Im1hZ2FyZUBleGFtcGxlLmNvbSIsImV4cCI6MTc4MTI2MDg0MSwiaXNzIjoiaHR0cDovL2xvY2FsaG9zdDo1MDAwIiwiYXVkIjoiaHR0cDovL2xvY2FsaG9zdDo1MDAwIn0.-xH3h4vWCLn8K2-iFkh-mvWn9mWb7PCE7DNbiOeDkKQ

###

POST http://localhost:8888/api/timebills
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJtYWdhcmVAZXhhbXBsZS5jb20iLCJqdGkiOiJkNzgxNTNjNC1iYjM5LTQwNjYtYTUxNy1hMGFhMDcwMTEyOWUiLCJ1bmlxdWVfbmFtZSI6Im1hZ2FyZUBleGFtcGxlLmNvbSIsImV4cCI6MTc4MTI2MDg0MSwiaXNzIjoiaHR0cDovL2xvY2FsaG9zdDo1MDAwIiwiYXVkIjoiaHR0cDovL2xvY2FsaG9zdDo1MDAwIn0.-xH3h4vWCLn8K2-iFkh-mvWn9mWb7PCE7DNbiOeDkKQ

{
    "hoursWorked": 3.0,
    "rate": 250.00,
    "date": "2023-05-05",
    "work": "I did a thing...",
    "customerId": 1,
    "employeeId": 1
}

###

GET http://localhost:8888/api/customers/1/timebills

###

GET http://localhost:8888/api/customers/1/timebills/10

### 

POST http://localhost:8888/api/auth/token
Content-Type: application/json

{
    "username": "magare@example.com",
    "password": "qweR!1234",
    "email": "magare@example.com"
}

###

GET http://localhost:8888/api/employees
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJtYWdhcmVAZXhhbXBsZS5jb20iLCJqdGkiOiJhZWRjMGMwYi0zZDg5LTQzOTAtYjJkYS01YTgzMmQ1ZmMwMTkiLCJ1bmlxdWVfbmFtZSI6Im1hZ2FyZUBleGFtcGxlLmNvbSIsImV4cCI6MTc4MjA3NzcxOCwiaXNzIjoiaHR0cDovL2xvY2FsaG9zdDo1MDAwIiwiYXVkIjoiaHR0cDovL2xvY2FsaG9zdDo1MDAwIn0.e2iHcC5awHBsBS1uyRiLL-eFcaigGMC1c4WFs6vneBM

###

GET http://localhost:8888/api/customers
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJtYWdhcmVAZXhhbXBsZS5jb20iLCJqdGkiOiI4NjliOTA4Zi1jZDJmLTQ2YzAtYWYxMS0zNmE4ZDQ4MWUxN2YiLCJ1bmlxdWVfbmFtZSI6Im1hZ2FyZUBleGFtcGxlLmNvbSIsImV4cCI6MTc4MjA3NzY4MSwiaXNzIjoiaHR0cDovL2xvY2FsaG9zdDo1MDAwIiwiYXVkIjoiaHR0cDovL2xvY2FsaG9zdDo1MDAwIn0.zwxC2nVrlG1r82CEy4QswRvCeJ81cQC-rKYU1AgO74Y