GET http://localhost:8888/api/customers
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJtYWdhcmVAZXhhbXBsZS5jb20iLCJqdGkiOiJkNzgxNTNjNC1iYjM5LTQwNjYtYTUxNy1hMGFhMDcwMTEyOWUiLCJ1bmlxdWVfbmFtZSI6Im1hZ2FyZUBleGFtcGxlLmNvbSIsImV4cCI6MTc4MTI2MDg0MSwiaXNzIjoiaHR0cDovL2xvY2FsaG9zdDo1MDAwIiwiYXVkIjoiaHR0cDovL2xvY2FsaG9zdDo1MDAwIn0.-xH3h4vWCLn8K2-iFkh-mvWn9mWb7PCE7DNbiOeDkKQ

###

GET http://localhost:8888/api/customers?withAddresses=true

###

GET http://localhost:8888/api/customers/1

###

GET http://localhost:8888/api/timebills/9
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJtYWdhcmVAZXhhbXBsZS5jb20iLCJqdGkiOiJkNzgxNTNjNC1iYjM5LTQwNjYtYTUxNy1hMGFhMDcwMTEyOWUiLCJ1bmlxdWVfbmFtZSI6Im1hZ2FyZUBleGFtcGxlLmNvbSIsImV4cCI6MTc4MTI2MDg0MSwiaXNzIjoiaHR0cDovL2xvY2FsaG9zdDo1MDAwIiwiYXVkIjoiaHR0cDovL2xvY2FsaG9zdDo1MDAwIn0.-xH3h4vWCLn8K2-iFkh-mvWn9mWb7PCE7DNbiOeDkKQ

###

POST http://localhost:8888/api/timebills
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJtYWdhcmVAZXhhbXBsZS5jb20iLCJqdGkiOiJkNzgxNTNjNC1iYjM5LTQwNjYtYTUxNy1hMGFhMDcwMTEyOWUiLCJ1bmlxdWVfbmFtZSI6Im1hZ2FyZUBleGFtcGxlLmNvbSIsImV4cCI6MTc4MTI2MDg0MSwiaXNzIjoiaHR0cDovL2xvY2FsaG9zdDo1MDAwIiwiYXVkIjoiaHR0cDovL2xvY2FsaG9zdDo1MDAwIn0.-xH3h4vWCLn8K2-iFkh-mvWn9mWb7PCE7DNbiOeDkKQ

{
    "hoursWorked": 3.0,
    "rate": 250.00,
    "date": "2023-05-05",
    "work": "I did a thing...",
    "customerId": 1,
    "employeeId": 1
}

###

GET http://localhost:8888/api/customers/1/timebills

###

GET http://localhost:8888/api/customers/1/timebills/10

### 

POST http://localhost:8888/api/auth/token
Content-Type: application/json

{
    "username": "magare@example.com",
    "password": "qweR!1234",
    "email": "magare@example.com"
}